### ISSUE TITLE
Zeitwerk::Error when using autoload_static_config_path = "config/configs"

### ISSUE THREAD

**Issue by wscourge** [palkan/anyway_config#110]
## What did you do?

I run the following:
```
rails new anyway_config -d postgresql
bundle add anyway_config
rails g anyway:install --configs-path=config/configs
```
then I uncommented `config.anyway_config.autoload_static_config_path = "config/configs"` in _config/application.rb_ file and executed:
```
rails g anyway:config database username password
```
but it fails on the aforementioned uncommented line of code upon any `rails` process (`console`, `server`). It does work with `app/config`.

## What did you expect to happen?

I expected it not to fail.

## What actually happened?

I got the following Zeitwerk error.

```
$ rails g anyway:config database username password                                                            
/Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:471:in `block (3 levels) in raise_if_conflicting_directory': loader (Zeitwerk::Error)

#<Zeitwerk::Loader:0x00000001103de120
 @autoloaded_dirs=[],
 @autoloads={},
 @collapse_dirs=#<Set: {}>,
 @collapse_glob_patterns=#<Set: {}>,
 @eager_load_exclusions=#<Set: {}>,
 @eager_loaded=false,
 @ignored_glob_patterns=#<Set: {}>,
 @ignored_paths=#<Set: {}>,
 @inflector=Rails::Autoloaders::Inflector,
 @initialized_at=2023-01-16 16:23:48.376379 +0100,
 @logger=nil,
 @mutex=#<Thread::Mutex:0x00000001121ca4b8>,
 @mutex2=#<Thread::Mutex:0x00000001121ca490>,
 @namespace_dirs={},
 @on_load_callbacks={},
 @on_setup_callbacks=[],
 @on_unload_callbacks={},
 @reloading_enabled=false,
 @roots={},
 @setup=false,
 @shadowed_files=#<Set: {}>,
 @tag="anyway.config",
 @to_unload={}>
wants to manage directory /Users/me/ws/tzif.io/hix/try/anyway_config/config/configs, which is already managed by

#<Zeitwerk::Loader:0x00000001103de260
 @autoloaded_dirs=[],
 @autoloads={},
 @collapse_dirs=#<Set: {}>,
 @collapse_glob_patterns=#<Set: {}>,
 @eager_load_exclusions=#<Set: {}>,
 @eager_loaded=false,
 @ignored_glob_patterns=#<Set: {}>,
 @ignored_paths=#<Set: {}>,
 @inflector=Rails::Autoloaders::Inflector,
 @initialized_at=2023-01-16 16:23:48.375365 +0100,
 @logger=nil,
 @mutex=#<Thread::Mutex:0x00000001124153a8>,
 @mutex2=#<Thread::Mutex:0x0000000112415380>,
 @namespace_dirs={},
 @on_load_callbacks={},
 @on_setup_callbacks=[],
 @on_unload_callbacks={},
 @reloading_enabled=false,
 @roots={"/Users/me/ws/tzif.io/hix/try/anyway_config/config/configs"=>Object},
 @setup=false,
 @shadowed_files=#<Set: {}>,
 @tag="anyway.config",
 @to_unload={}>


	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:465:in `each_key'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:465:in `block (2 levels) in raise_if_conflicting_directory'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:461:in `each'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:461:in `block in raise_if_conflicting_directory'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:458:in `synchronize'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:458:in `raise_if_conflicting_directory'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/config.rb:123:in `push_dir'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/anyway_config-2.3.0/lib/anyway/rails/settings.rb:30:in `block in autoload_static_config_path='
	from <internal:kernel>:90:in `tap'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/anyway_config-2.3.0/lib/anyway/rails/settings.rb:27:in `autoload_static_config_path='
	from /Users/me/ws/tzif.io/hix/try/anyway_config/config/application.rb:13:in `<class:Application>'
	from /Users/me/ws/tzif.io/hix/try/anyway_config/config/application.rb:10:in `<module:AnywayConfig>'
	from /Users/me/ws/tzif.io/hix/try/anyway_config/config/application.rb:9:in `<main>'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4/lib/rails/command/actions.rb:22:in `require_application!'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/me/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

## Additional context

none

## Environment

**Ruby Version:** 3.2.0

**Framework Version (Rails, whatever):** 7.0.4

**Anyway Config Version:** 2.3.0

**Comment by palkan** [comment]
Thanks for reporting.

Fixed and released in 2.3.1.

**Comment by darkporpoise** [comment]
I'm getting this error now as well. Am I right in thinking that this doesn't matter because `config/configs` is static autoloaded by default anyway?

Ruby Version: 3.1.4
Framework Version (Rails, whatever): 6.0.6.1
Anyway Config Version: 2.6.4

<details>
<summary>Error</summary>

```Ruby
rails g anyway:config config_class config_value
```

```
/app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:542:in `block (3 levels) in raise_if_conflicting_directory': loader

#<Zeitwerk::Loader:0x0000ffff956596a0
 @autoloaded_dirs=[],
 @autoloads={},
 @collapse_dirs=#<Set: {}>,
 @collapse_glob_patterns=#<Set: {}>,
 @dirs_autoload_monitor=#<Monitor:0x0000ffff95658f70>,
 @eager_load_exclusions=#<Set: {}>,
 @eager_loaded=false,
 @ignored_glob_patterns=#<Set: {}>,
 @ignored_paths=#<Set: {}>,
 @inflector=ActiveSupport::Dependencies::ZeitwerkIntegration::Inflector,
 @initialized_at="2024-05-24T10:30:59.787+00:00",
 @logger=nil,
 @mutex=#<Thread::Mutex:0x0000ffff95658fc0>,
 @namespace_dirs={},
 @on_load_callbacks={},
 @on_setup_callbacks=[],
 @on_unload_callbacks={},
 @reloading_enabled=false,
 @roots={},
 @setup=false,
 @shadowed_files=#<Set: {}>,
 @tag="anyway.config",
 @to_unload={}>


wants to manage directory /app/config/configs, which is already managed by

#<Zeitwerk::Loader:0x0000ffff95660298
 @autoloaded_dirs=[],
 @autoloads={},
 @collapse_dirs=#<Set: {}>,
 @collapse_glob_patterns=#<Set: {}>,
 @dirs_autoload_monitor=#<Monitor:0x0000ffff9565fb68>,
 @eager_load_exclusions=#<Set: {}>,
 @eager_loaded=false,
 @ignored_glob_patterns=#<Set: {}>,
 @ignored_paths=#<Set: {}>,
 @inflector=ActiveSupport::Dependencies::ZeitwerkIntegration::Inflector,
 @initialized_at="2024-05-24T10:30:59.785+00:00",
 @logger=nil,
 @mutex=#<Thread::Mutex:0x0000ffff9565fbb8>,
 @namespace_dirs={},
 @on_load_callbacks={},
 @on_setup_callbacks=[],
 @on_unload_callbacks={},
 @reloading_enabled=false,
 @roots={"/app/config/configs"=>Object},
 @setup=false,
 @shadowed_files=#<Set: {}>,
 @tag="anyway.config",
 @to_unload={}>

 (Zeitwerk::Error)
        from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:536:in `each_key'
        from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:536:in `block (2 levels) in raise_if_conflicting_directory'
        from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:532:in `each'
        from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:532:in `block in raise_if_conflicting_directory'
        from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:529:in `synchronize'
        from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:529:in `raise_if_conflicting_directory'
        from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/config.rb:122:in `push_dir'
        from /app/vendor/ruby/3.1.0/gems/anyway_config-2.6.4/lib/anyway/rails/settings.rb:38:in `block in autoload_static_config_path='
        from <internal:kernel>:90:in `tap'
        from /app/vendor/ruby/3.1.0/gems/anyway_config-2.6.4/lib/anyway/rails/settings.rb:30:in `autoload_static_config_path='
        from /app/config/application.rb:28:in `<class:Application>'
        from /app/config/application.rb:10:in `<module:MyApp>'
        from /app/config/application.rb:9:in `<top (required)>'
        from /app/vendor/ruby/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
        from /app/vendor/ruby/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
        from /app/vendor/ruby/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
        from /app/vendor/ruby/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        from /app/vendor/ruby/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        from /app/vendor/ruby/3.1.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        from /app/vendor/ruby/3.1.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'
```

</details>

**Comment by palkan** [comment]
> /app/vendor/ruby/3.1.0/gems/spring-2.1.1/lib/spring/application.rb

I bet it's something related to Spring; could please run without Spring and see if it fails?

**Comment by darkporpoise** [comment]
Thanks for taking a look. I still get the error with Spring disabled:

```Ruby
DISABLE_SPRING=true rails s
```

<details><summary>error</summary>

/app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:542:in `block (3 levels) in raise_if_conflicting_directory': loader (Zeitwerk::Error)

#<Zeitwerk::Loader:0x0000ffffa9ba1db0
 @autoloaded_dirs=[],
 @autoloads={},
 @collapse_dirs=#<Set: {}>,
 @collapse_glob_patterns=#<Set: {}>,
 @dirs_autoload_monitor=#<Monitor:0x0000ffffa9ba1680>,
 @eager_load_exclusions=#<Set: {}>,
 @eager_loaded=false,
 @ignored_glob_patterns=#<Set: {}>,
 @ignored_paths=#<Set: {}>,
 @inflector=ActiveSupport::Dependencies::ZeitwerkIntegration::Inflector,
 @initialized_at="2024-05-30T09:01:49.247+00:00",
 @logger=nil,
 @mutex=#<Thread::Mutex:0x0000ffffa9ba16d0>,
 @namespace_dirs={},
 @on_load_callbacks={},
 @on_setup_callbacks=[],
 @on_unload_callbacks={},
 @reloading_enabled=false,
 @roots={},
 @setup=false,
 @shadowed_files=#<Set: {}>,
 @tag="anyway.config",
 @to_unload={}>


wants to manage directory /app/config/configs, which is already managed by

#<Zeitwerk::Loader:0x0000ffffa9ba9678
 @autoloaded_dirs=[],
 @autoloads={},
 @collapse_dirs=#<Set: {}>,
 @collapse_glob_patterns=#<Set: {}>,
 @dirs_autoload_monitor=#<Monitor:0x0000ffffa9ba8f70>,
 @eager_load_exclusions=#<Set: {}>,
 @eager_loaded=false,
 @ignored_glob_patterns=#<Set: {}>,
 @ignored_paths=#<Set: {}>,
 @inflector=ActiveSupport::Dependencies::ZeitwerkIntegration::Inflector,
 @initialized_at="2024-05-30T09:01:49.245+00:00",
 @logger=nil,
 @mutex=#<Thread::Mutex:0x0000ffffa9ba8fc0>,
 @namespace_dirs={},
 @on_load_callbacks={},
 @on_setup_callbacks=[],
 @on_unload_callbacks={},
 @reloading_enabled=false,
 @roots={"/app/config/configs"=>Object},
 @setup=false,
 @shadowed_files=#<Set: {}>,
 @tag="anyway.config",
 @to_unload={}>

	from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:536:in `each_key'
	from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:536:in `block (2 levels) in raise_if_conflicting_directory'
	from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:532:in `each'
	from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:532:in `block in raise_if_conflicting_directory'
	from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:529:in `synchronize'
	from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:529:in `raise_if_conflicting_directory'
	from /app/vendor/ruby/3.1.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/config.rb:122:in `push_dir'
	from /app/vendor/ruby/3.1.0/gems/anyway_config-2.6.4/lib/anyway/rails/settings.rb:38:in `block in autoload_static_config_path='
	from <internal:kernel>:90:in `tap'
	from /app/vendor/ruby/3.1.0/gems/anyway_config-2.6.4/lib/anyway/rails/settings.rb:30:in `autoload_static_config_path='
	from /app/config/application.rb:28:in `<class:Application>'
	from /app/config/application.rb:10:in `<module:TheHiringHub>'
	from /app/config/application.rb:9:in `<main>'
	from /app/vendor/ruby/3.1.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /app/vendor/ruby/3.1.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /app/vendor/ruby/3.1.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
	from /app/vendor/ruby/3.1.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /app/vendor/ruby/3.1.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
	from /app/vendor/ruby/3.1.0/gems/railties-6.0.6.1/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /app/vendor/ruby/3.1.0/gems/railties-6.0.6.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	from /app/vendor/ruby/3.1.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/ruby/3.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/ruby/3.1.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/ruby/3.1.0/gems/railties-6.0.6.1/lib/rails/command/base.rb:69:in `perform'
	from /app/vendor/ruby/3.1.0/gems/railties-6.0.6.1/lib/rails/command.rb:46:in `invoke'
	from /app/vendor/ruby/3.1.0/gems/railties-6.0.6.1/lib/rails/commands.rb:18:in `<main>'
	from /app/vendor/ruby/3.1.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /app/vendor/ruby/3.1.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:9:in `<main>'

</details>

**Comment by palkan** [comment]
@darkporpoise Thanks for checking.

Can you please show the value you assign to the `config.anyway_config.autoload_static_config_path` (here `config/application.rb:28`) ?

**Comment by darkporpoise** [comment]
```Ruby

    ### AnyWayConfig
    ## https://github.com/palkan/anyway_config

    ### Defaut location to check for YML files
    config.anyway_config.default_config_path = Rails.root.join("config", "configs")
    ### Location of static config classes. These are available in Initializers but are not reloaded.
    config.anyway_config.autoload_static_config_path = Rails.root.join("config", "configs")
    ### Check for top level known environment keys in config files.
    ## If any value is environment specific they all have to be. You can't mix and match within a file.
    config.anyway_config.future.use :unwrap_known_environments
    config.anyway_config.known_environments.concat %w[staging demo]
    ### Name of top level key to apply to all environments. Similar to YML anchor but allows deep-merging
    config.anyway_config.default_environmental_key = "default"

```

Line 28 is the `autoload_static_config_path`

**Comment by palkan** [comment]
Thanks! Since you're using the absolute path, this line doesn't work as it should do: https://github.com/palkan/anyway_config/blob/233248947ff0f9e5bac4b7aaea9648ae2c464928/lib/anyway/rails/settings.rb#L22

We use `config/configs` as the default path.

For now, you can either remove this configuration line (since it's already the default) or replace with:

```rb
config.anyway_config.autoload_static_config_path = "config/configs"
```

**Comment by darkporpoise** [comment]
Thank you. That makes sense.
